# Generated by Django 2.2.7 on 2019-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesshedule',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='classesshedule',
            name='day',
            field=models.DateField(),
        ),
    ]
